### ISSUE TITLE
Fonts are large

### ISSUE THREAD

**Issue by rennex** [Rob--W/open-in-browser#21]
I've set Windows 10 to 150% text size, because I use a 150 DPI monitor. The download popup looks abnormally large, like it was meant for 200 DPI. Here's a comparison:

<img width="487" alt="avkpic" src="https://user-images.githubusercontent.com/449856/32989523-8cb1b2f6-cd20-11e7-8113-fe1fdb69fa1f.png">

Versus a native dialog:

<img width="433" alt="avkpic-native" src="https://user-images.githubusercontent.com/449856/32989761-58127b34-cd25-11e7-9427-848c478404fa.png">

It's not a big issue, and better large than too small. But there's room to tweak it 😄

**Comment by Rob--W** [comment]
Thanks for this report. @BjornRuytenberg already reported that the UI looks different, and I filed it as #18. I will however keep this issue open since it mentions a specific issue, whereas my other report is just a generic meta bug.

**Comment by Rob--W** [comment]
The issue turned out to be OS-independent. I pushed a fix.

Can you try it out and see whether the dialog appears as expected now?

You can either clone the repo and use `about:debugging` to load the extension, or use the devtools for the dialog and manually apply part of the fix (the input fields are also addressed by my patch, but not in the next snippet):

```js
document.body.style.fontSize = '1rem';
```

**Comment by BjornRuytenberg** [comment]
The fonts still seem too large, and it looks like the input field use a different font. Here are the settings that work for me:

```css
body {
    font-size: 0.75rem;
    font-family: 'Segoe UI', 'Lucida Grande', 'Ubuntu', sans-serif;
    background-color: ButtonFace;
    color: ButtonText;
}

input, select {
    font-family: 'Segoe UI', 'Lucida Grande', 'Ubuntu', sans-serif;
    font-size: 0.75rem;
}
```

This works regardless of DPI settings. Here's the result on 90 DPI:
![90dpi](https://user-images.githubusercontent.com/27902767/32993814-e29f9d26-cd5d-11e7-9087-a9dbc1575b7a.png)

On 150 DPI:
![150dpi](https://user-images.githubusercontent.com/27902767/32993815-e48c3e8c-cd5d-11e7-87ab-87a568498311.PNG)

Obviously the dialog's dimensions still need to be adjusted accordingly.
